import { flutterRound, parseFlutterDouble } from '@/utils/flutter-number';
import React from 'react';
import { KeyboardAvoidingView, Modal, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { AppText } from '@/components/app-text';
import { MaterialIcon } from '@/components/material-icon';
import type { MaterialIconName } from '@/constants/material-icons.generated';
import type { RevenueLedger } from '@/models/revenue-ledger';
import type { LookupOption } from '@/repositories/lookups-repository';
import type { RevenueEntryUpdate } from '@/repositories/revenue-repository';
import { useAppTheme } from '@/theme/theme';

export function EditRevenueEntryDialog({ visible, entry, gyms, plans, onClose, onSave }: { visible: boolean; entry: RevenueLedger | null; gyms: LookupOption[]; plans: LookupOption[]; onClose: () => void; onSave: (update: RevenueEntryUpdate) => void }) {
  const { colors } = useAppTheme(); const [amount, setAmount] = React.useState(entry ? (entry.amountCents / 100).toFixed(2) : ''); const [notes, setNotes] = React.useState(entry?.notes ?? ''); const [payment, setPayment] = React.useState(entry?.paymentMethod ?? 'cash'); const [gymId, setGymId] = React.useState<string | undefined>(entry?.gym?.id); const [planId, setPlanId] = React.useState<string | undefined>(entry?.plan?.id); const [open, setOpen] = React.useState<'payment' | 'gym' | 'plan' | null>(null); const [error, setError] = React.useState<string>();
  if (!entry) return null;
  const save = () => { const numeric = parseFlutterDouble(amount); if (numeric === null || !Number.isFinite(numeric) || numeric <= 0) { setError('Suma invalidă'); return; } onSave({ amount_cents: flutterRound(numeric * 100), payment_method: payment, gym_id: gymId ?? null, plan_id: planId ?? null, notes: notes.trim() || null }); };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><KeyboardAvoidingView behavior={process.env.EXPO_OS === 'ios' ? 'padding' : undefined} style={styles.backdrop}><View style={[styles.dialog, { backgroundColor: colors.surface }]}><AppText variant="titleLarge" style={styles.title}>Editează Tranzacție</AppText><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Field label="Suma (RON)" icon="attach_money"><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" selectionColor={colors.primary} style={[styles.input, { color: colors.onSurface }]} /></Field>{error ? <AppText variant="bodySmall" color={colors.error}>{error}</AppText> : null}
    <Select label="Metodă de Plată" icon="payment" value={payment === 'card' ? '💳 Card' : '💵 Cash'} open={open === 'payment'} onToggle={() => setOpen((current) => current === 'payment' ? null : 'payment')}><Option label="💵 Cash" selected={payment === 'cash'} onPress={() => { setPayment('cash'); setOpen(null); }} /><Option label="💳 Card" selected={payment === 'card'} onPress={() => { setPayment('card'); setOpen(null); }} /></Select>
    <Select label="Sală" icon="fitness_center" value={gyms.find((gym) => gym.id === gymId)?.name ?? 'Niciuna'} open={open === 'gym'} onToggle={() => setOpen((current) => current === 'gym' ? null : 'gym')}><Option label="Niciuna" selected={!gymId} onPress={() => { setGymId(undefined); setOpen(null); }} />{gyms.map((gym) => <Option key={gym.id} label={gym.name} selected={gymId === gym.id} onPress={() => { setGymId(gym.id); setOpen(null); }} />)}</Select>
    <Select label="Plan Abonament" icon="card_membership" value={plans.find((plan) => plan.id === planId)?.name ?? 'Niciun plan'} open={open === 'plan'} onToggle={() => setOpen((current) => current === 'plan' ? null : 'plan')}><Option label="Niciun plan" selected={!planId} onPress={() => { setPlanId(undefined); setOpen(null); }} />{plans.map((plan) => <Option key={plan.id} label={plan.name} selected={planId === plan.id} onPress={() => { setPlanId(plan.id); setOpen(null); }} />)}</Select>
    <Field label="Notițe (opțional)" icon="notes"><TextInput value={notes} onChangeText={setNotes} multiline numberOfLines={3} textAlignVertical="top" selectionColor={colors.primary} style={[styles.input, styles.notes, { color: colors.onSurface }]} /></Field>
  </ScrollView><View style={styles.actions}><Pressable onPress={onClose} style={styles.action}><AppText color={colors.primary}>Anulează</AppText></Pressable><Pressable onPress={save} style={[styles.action, styles.save, { backgroundColor: colors.primary }]}><AppText color={colors.onPrimary} style={styles.bold}>Salvează</AppText></Pressable></View></View></KeyboardAvoidingView></Modal>;
}
function Field({ label, icon, children }: React.PropsWithChildren<{ label: string; icon: MaterialIconName }>) { const { colors } = useAppTheme(); return <View style={[styles.field, { borderColor: colors.outline }]}><MaterialIcon name={icon} size={24} color={colors.onSurfaceVariant} /><View style={styles.fieldCopy}><AppText variant="bodySmall" color={colors.onSurfaceVariant}>{label}</AppText>{children}</View></View>; }
function Select({ label, icon, value, open, onToggle, children }: React.PropsWithChildren<{ label: string; icon: MaterialIconName; value: string; open: boolean; onToggle: () => void }>) { const { colors } = useAppTheme(); return <View><Pressable onPress={onToggle}><View style={[styles.field, { borderColor: colors.outline }]}><MaterialIcon name={icon} size={24} color={colors.onSurfaceVariant} /><View style={styles.fieldCopy}><AppText variant="bodySmall" color={colors.onSurfaceVariant}>{label}</AppText><AppText variant="bodyLarge">{value}</AppText></View><MaterialIcon name="arrow_drop_down" size={24} color={colors.onSurfaceVariant} style={open ? styles.rotate : undefined} /></View></Pressable>{open ? <View style={[styles.menu, { backgroundColor: colors.surfaceContainerHigh, borderColor: colors.outlineVariant }]}>{children}</View> : null}</View>; }
function Option({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { colors } = useAppTheme(); return <Pressable onPress={onPress} style={styles.option}><AppText color={selected ? colors.primary : undefined} style={selected ? styles.bold : undefined}>{label}</AppText></Pressable>; }
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: '#00000066', justifyContent: 'center', padding: 24 }, dialog: { maxHeight: '85%', borderRadius: 28, overflow: 'hidden' }, title: { fontWeight: '700', padding: 24, paddingBottom: 12 }, content: { paddingHorizontal: 24, paddingBottom: 8, gap: 16 }, field: { minHeight: 56, borderWidth: 1, borderRadius: 4, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 }, fieldCopy: { flex: 1, marginLeft: 12 }, input: { fontSize: 16, lineHeight: 22, paddingVertical: 0 }, notes: { minHeight: 64, paddingTop: 4 }, menu: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 8, overflow: 'hidden', marginTop: 4 }, option: { paddingHorizontal: 16, paddingVertical: 12 }, rotate: { transform: [{ rotate: '180deg' }] }, actions: { flexDirection: 'row', justifyContent: 'flex-end', padding: 16 }, action: { minHeight: 44, minWidth: 90, alignItems: 'center', justifyContent: 'center', borderRadius: 22, marginLeft: 8 }, save: { paddingHorizontal: 16 }, bold: { fontWeight: '700' } });
