import 'package:powersync/powersync.dart';

const powersyncSchema = Schema([
  Table(
    'profiles',
    [
      Column.text('full_name'),
      Column.text('phone'),
      Column.text('email'),
      Column.text('created_at'),
      Column.text('updated_at'),
      Column.integer('is_admin'),
      Column.integer('is_employee'),
    ],
    indexes: [
      Index('profiles_name', [IndexedColumn('full_name')]),
      Index('profiles_phone', [IndexedColumn('phone')]),
      Index('profiles_email', [IndexedColumn('email')]),
    ],
  ),
  Table(
    'memberships',
    [
      Column.text('user_id'),
      Column.text('plan_id'),
      Column.text('membership_type'),
      Column.text('start_date'),
      Column.text('effective_start_date'),
      Column.text('end_date'),
      Column.integer('duration_months'),
      Column.integer('duration_days'),
      Column.integer('is_active'),
      Column.integer('is_student'),
      Column.integer('price_paid_cents'),
      Column.text('currency'),
      Column.text('payment_method'),
      Column.text('sold_at_gym_id'),
      Column.text('qr_code_data'),
      Column.text('cancel_reason'),
      Column.text('created_at'),
      Column.text('updated_at'),
      Column.text('canceled_at'),
      Column.text('created_by_user_id'),
      Column.integer('is_frozen'),
      Column.text('frozen_at'),
      Column.text('frozen_by_user_id'),
      Column.integer('days_left_when_frozen'),
      Column.integer('days_left'),
      Column.text('freeze_type'),
      Column.text('auto_unfreeze_at'),
    ],
    indexes: [
      Index('memberships_user', [IndexedColumn('user_id')]),
      Index('memberships_plan', [IndexedColumn('plan_id')]),
      Index('memberships_gym', [IndexedColumn('sold_at_gym_id')]),
      Index('memberships_end_date', [IndexedColumn('end_date')]),
    ],
  ),
  Table(
    'check_ins',
    [
      Column.text('user_id'),
      Column.text('gym_id'),
      Column.text('membership_id'),
      Column.text('status'),
      Column.text('message'),
      Column.integer('days_left'),
      Column.integer('shown_to_user'),
      Column.text('created_at'),
      Column.text('method'),
      Column.text('scanned_by'),
    ],
    indexes: [
      Index('check_ins_user_created', [
        IndexedColumn('user_id'),
        IndexedColumn('created_at'),
      ]),
      Index('check_ins_gym_created', [
        IndexedColumn('gym_id'),
        IndexedColumn('created_at'),
      ]),
    ],
  ),
  Table(
    'gyms',
    [
      Column.text('name'),
      Column.text('description'),
      Column.text('address'),
      Column.text('city'),
      Column.text('state'),
      Column.text('postal_code'),
      Column.text('phone'),
      Column.text('email'),
      Column.text('opening_hours'),
      Column.real('latitude'),
      Column.real('longitude'),
      Column.text('facilities'),
      Column.text('images'),
      Column.text('created_at'),
      Column.integer('capacity_hint'),
      Column.text('timezone'),
      Column.text('sauna_hours'),
      Column.text('good_morning_hour'),
    ],
    indexes: [
      Index('gyms_name', [IndexedColumn('name')]),
    ],
  ),
  Table(
    'membership_plans',
    [
      Column.text('name'),
      Column.text('plan_kind'),
      Column.text('tier'),
      Column.text('gym_id'),
      Column.integer('monthly_price_cents'),
      Column.integer('yearly_price_cents'),
      Column.integer('student_discount_cents'),
      Column.text('currency'),
      Column.integer('is_active'),
      Column.text('created_at'),
      Column.text('updated_at'),
      Column.integer('is_family_plan'),
      Column.integer('max_family_members'),
      Column.integer('is_good_morning'),
      Column.integer('duration_months'),
      Column.integer('duration_days'),
    ],
    indexes: [
      Index('membership_plans_active_name', [
        IndexedColumn('is_active'),
        IndexedColumn('name'),
      ]),
    ],
  ),
  Table(
    'membership_plan_access',
    [Column.text('plan_id'), Column.text('gym_id')],
    indexes: [
      Index('membership_plan_access_plan', [IndexedColumn('plan_id')]),
      Index('membership_plan_access_gym', [IndexedColumn('gym_id')]),
    ],
  ),
  Table(
    'family_memberships',
    [
      Column.text('user_id'),
      Column.text('membership_id'),
      Column.text('created_at'),
    ],
    indexes: [
      Index('family_memberships_user', [IndexedColumn('user_id')]),
      Index('family_memberships_membership', [IndexedColumn('membership_id')]),
    ],
  ),
  Table(
    'membership_events',
    [
      Column.text('membership_id'),
      Column.text('event_type'),
      Column.text('at'),
      Column.text('by_user'),
      Column.text('notes'),
      Column.integer('delta_days'),
      Column.integer('delta_cents'),
      Column.text('old_start_date'),
      Column.text('old_end_date'),
      Column.text('new_start_date'),
      Column.text('new_end_date'),
      Column.text('plan_id'),
    ],
    indexes: [
      Index('membership_events_membership', [IndexedColumn('membership_id')]),
    ],
  ),
  Table(
    'employees',
    [
      Column.text('user_id'),
      Column.text('gym_id'),
      Column.text('role'),
      Column.integer('is_active'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('employees_user', [IndexedColumn('user_id')]),
    ],
  ),
  Table(
    'revenue_ledger',
    [
      Column.text('paid_at'),
      Column.text('plan_id'),
      Column.text('membership_id'),
      Column.text('gym_id'),
      Column.integer('amount_cents'),
      Column.text('currency'),
      Column.text('source'),
      Column.text('notes'),
      Column.text('created_at'),
      Column.text('entry_kind'),
      Column.text('payment_method'),
      Column.text('idempotency_key'),
      Column.text('recorded_by'),
      Column.text('client_user_id'),
      Column.text('client_full_name'),
      Column.integer('is_deleted'),
      Column.text('deleted_at'),
      Column.text('deleted_by'),
    ],
    indexes: [
      Index('revenue_ledger_membership', [IndexedColumn('membership_id')]),
    ],
  ),
  Table('admin_analytics_summary', [
    Column.integer('wau'),
    Column.integer('mau'),
    Column.integer('yesterday_dau'),
    Column.real('stickiness_percent'),
    Column.text('updated_at'),
  ]),
]);
