import { column, Schema, Table } from '@powersync/react-native';

export const appSchema = new Schema({
  profiles: new Table(
    {
      full_name: column.text,
      phone: column.text,
      email: column.text,
      created_at: column.text,
      updated_at: column.text,
      is_admin: column.integer,
      is_employee: column.integer,
    },
    {
      indexes: {
        profiles_name: ['full_name'],
        profiles_phone: ['phone'],
        profiles_email: ['email'],
      },
    },
  ),
  memberships: new Table(
    {
      user_id: column.text,
      plan_id: column.text,
      membership_type: column.text,
      start_date: column.text,
      effective_start_date: column.text,
      end_date: column.text,
      duration_months: column.integer,
      duration_days: column.integer,
      is_active: column.integer,
      is_student: column.integer,
      price_paid_cents: column.integer,
      currency: column.text,
      payment_method: column.text,
      sold_at_gym_id: column.text,
      qr_code_data: column.text,
      cancel_reason: column.text,
      created_at: column.text,
      updated_at: column.text,
      canceled_at: column.text,
      created_by_user_id: column.text,
      is_frozen: column.integer,
      frozen_at: column.text,
      frozen_by_user_id: column.text,
      days_left_when_frozen: column.integer,
      days_left: column.integer,
      freeze_type: column.text,
      auto_unfreeze_at: column.text,
    },
    {
      indexes: {
        memberships_user: ['user_id'],
        memberships_plan: ['plan_id'],
        memberships_gym: ['sold_at_gym_id'],
        memberships_end_date: ['end_date'],
      },
    },
  ),
  check_ins: new Table(
    {
      user_id: column.text,
      gym_id: column.text,
      membership_id: column.text,
      status: column.text,
      message: column.text,
      days_left: column.integer,
      shown_to_user: column.integer,
      created_at: column.text,
      method: column.text,
      scanned_by: column.text,
    },
    {
      indexes: {
        check_ins_user_created: ['user_id', 'created_at'],
        check_ins_gym_created: ['gym_id', 'created_at'],
      },
    },
  ),
  gyms: new Table(
    {
      name: column.text,
      description: column.text,
      address: column.text,
      city: column.text,
      state: column.text,
      postal_code: column.text,
      phone: column.text,
      email: column.text,
      opening_hours: column.text,
      latitude: column.real,
      longitude: column.real,
      facilities: column.text,
      images: column.text,
      created_at: column.text,
      capacity_hint: column.integer,
      timezone: column.text,
      sauna_hours: column.text,
      good_morning_hour: column.text,
    },
    { indexes: { gyms_name: ['name'] } },
  ),
  membership_plans: new Table(
    {
      name: column.text,
      plan_kind: column.text,
      tier: column.text,
      gym_id: column.text,
      monthly_price_cents: column.integer,
      yearly_price_cents: column.integer,
      student_discount_cents: column.integer,
      currency: column.text,
      is_active: column.integer,
      created_at: column.text,
      updated_at: column.text,
      is_family_plan: column.integer,
      max_family_members: column.integer,
      is_good_morning: column.integer,
      duration_months: column.integer,
      duration_days: column.integer,
    },
    { indexes: { membership_plans_active_name: ['is_active', 'name'] } },
  ),
  membership_plan_access: new Table(
    { plan_id: column.text, gym_id: column.text },
    {
      indexes: {
        membership_plan_access_plan: ['plan_id'],
        membership_plan_access_gym: ['gym_id'],
      },
    },
  ),
  family_memberships: new Table(
    { user_id: column.text, membership_id: column.text, created_at: column.text },
    {
      indexes: {
        family_memberships_user: ['user_id'],
        family_memberships_membership: ['membership_id'],
      },
    },
  ),
  membership_freeze_schedules: new Table(
    {
      membership_id: column.text,
      duration_days: column.integer,
      freeze_type: column.text,
      scheduled_start_date: column.text,
      status: column.text,
      created_by_user_id: column.text,
      canceled_by_user_id: column.text,
      started_at: column.text,
      canceled_at: column.text,
      skipped_at: column.text,
      skip_reason: column.text,
      notes: column.text,
      created_at: column.text,
      updated_at: column.text,
    },
    { indexes: { freeze_schedules_membership: ['membership_id', 'status'] } },
  ),
  membership_events: new Table(
    {
      membership_id: column.text,
      event_type: column.text,
      at: column.text,
      by_user: column.text,
      notes: column.text,
      delta_days: column.integer,
      delta_cents: column.integer,
      old_start_date: column.text,
      old_end_date: column.text,
      new_start_date: column.text,
      new_end_date: column.text,
      plan_id: column.text,
    },
    { indexes: { membership_events_membership: ['membership_id'] } },
  ),
  employees: new Table(
    {
      user_id: column.text,
      gym_id: column.text,
      role: column.text,
      is_active: column.integer,
      created_at: column.text,
      updated_at: column.text,
    },
    { indexes: { employees_user: ['user_id'] } },
  ),
  revenue_ledger: new Table(
    {
      paid_at: column.text,
      plan_id: column.text,
      membership_id: column.text,
      gym_id: column.text,
      amount_cents: column.integer,
      currency: column.text,
      source: column.text,
      notes: column.text,
      created_at: column.text,
      entry_kind: column.text,
      payment_method: column.text,
      idempotency_key: column.text,
      recorded_by: column.text,
      client_user_id: column.text,
      client_full_name: column.text,
      is_deleted: column.integer,
      deleted_at: column.text,
      deleted_by: column.text,
    },
    { indexes: { revenue_ledger_membership: ['membership_id'] } },
  ),
  admin_analytics_summary: new Table({
    wau: column.integer,
    mau: column.integer,
    yesterday_dau: column.integer,
    stickiness_percent: column.real,
    updated_at: column.text,
  }),
});

export type AppSchema = (typeof appSchema)['types'];
